name: formtestovoe

services:
  php-apache:
    build: .
    ports:
      - "8081:80"
    volumes:
      - /var/www/html
    networks:
      - backend
    depends_on:
      - db
      - phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    links:
      - db
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mysql:8
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=SAmsuNG246ubuntu
      - MYSQL_DATABASE=formtestovoe
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend

volumes:
  db-volume:
networks:
  backend:
    driver: bridge