name: formtestovoe

services:
  php-apache:
    build: .
    ports:
      - "8088:80"
    environment:
      - APP_URL=http://localhost:8088
      - DB_HOST=mysql
    volumes:
      - /var/www/html
    networks:
      - backend
  db:
    image: mysql:8
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=SAmsuNG246ubuntu
      - MYSQL_DATABASE=formtestovoe
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend

volumes:
  db-volume:
networks:
  backend: